name: Publish Plugin to JetBrains Marketplace

# Trigger on:
# 1. Manual workflow dispatch for testing
# 2. Tag push (e.g., v1.0.0)
on:
  workflow_dispatch:
    inputs:
      channel:
        description: 'Release channel (default, beta, eap)'
        required: true
        default: 'default'
        type: choice
        options:
          - default
          - beta
          - eap
  
  push:
    tags:
      - 'v*.*.*'  # Matches v1.0.0, v2.1.3, etc.

jobs:
  # Pre-publish validation
  validate:
    name: Validate Before Publishing
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      
      - name: Run all verification tasks
        run: ./gradlew verify --no-daemon
      
      - name: Verify plugin configuration
        run: ./gradlew verifyPluginConfiguration --no-daemon
      
      - name: Build plugin distribution
        run: ./gradlew buildPlugin --no-daemon
      
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: plugin-artifact
          path: build/distributions/*.zip
          retention-days: 7

  # Publish to JetBrains Marketplace
  publish:
    name: Publish to Marketplace
    needs: validate
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      
      - name: Extract version from tag
        if: github.event_name == 'push'
        id: extract_version
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          echo "Publishing version: $VERSION"
      
      - name: Determine release channel
        id: channel
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            CHANNEL="${{ github.event.inputs.channel }}"
          elif [[ "${{ github.ref }}" == *"beta"* ]]; then
            CHANNEL="beta"
          elif [[ "${{ github.ref }}" == *"eap"* ]]; then
            CHANNEL="eap"
          else
            CHANNEL="default"
          fi
          echo "CHANNEL=$CHANNEL" >> $GITHUB_OUTPUT
          echo "Release channel: $CHANNEL"
      
      - name: Publish plugin to JetBrains Marketplace
        env:
          JETBRAINS_MARKETPLACE_TOKEN: ${{ secrets.JETBRAINS_MARKETPLACE_TOKEN }}
        run: |
          ./gradlew publishPlugin \
            -Pchannel=${{ steps.channel.outputs.CHANNEL }} \
            --no-daemon
      
      - name: Upload distribution
        uses: actions/upload-artifact@v4
        with:
          name: plugin-distribution
          path: build/distributions/*.zip
          retention-days: 30
      
      - name: Create GitHub Release
        if: github.event_name == 'push'
        uses: softprops/action-gh-release@v1
        with:
          files: build/distributions/*.zip
          draft: false
          prerelease: ${{ contains(github.ref, 'beta') || contains(github.ref, 'eap') }}
          generate_release_notes: true
          body: |
            ## 🎉 Release ${{ steps.extract_version.outputs.VERSION }}
            
            This plugin has been automatically published to the [JetBrains Marketplace](https://plugins.jetbrains.com/plugin/com.shrikantbadwaik.jb-publish-tracker).
            
            ### 📦 Installation
            1. Open IntelliJ IDEA
            2. Go to **Settings/Preferences → Plugins**
            3. Search for "**Publish/Verify Tracker**"
            4. Click **Install**
            
            Or download the plugin ZIP below and install manually via **Install Plugin from Disk**.
            
            ### 📝 Full Changelog
            See [CHANGELOG.md](https://github.com/${{ github.repository }}/blob/main/CHANGELOG.md) for details.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Notify on success
        if: success()
        run: |
          echo "✅ Plugin successfully published to JetBrains Marketplace!"
          echo "🔗 View at: https://plugins.jetbrains.com/plugin/com.shrikantbadwaik.jb-publish-tracker"
      
      - name: Notify on failure
        if: failure()
        run: |
          echo "❌ Publishing failed! Check the logs above for details."
          exit 1

  # Post-publish verification
  verify-published:
    name: Verify Plugin on Marketplace
    needs: publish
    runs-on: ubuntu-latest
    if: success()
    
    steps:
      - name: Wait for marketplace processing
        run: sleep 30
      
      - name: Check plugin is available
        run: |
          PLUGIN_ID="com.shrikantbadwaik.jb-publish-tracker"
          RESPONSE=$(curl -s "https://plugins.jetbrains.com/api/plugins/${PLUGIN_ID}")
          
          if echo "$RESPONSE" | grep -q "\"id\":\"${PLUGIN_ID}\""; then
            echo "✅ Plugin is live on the marketplace!"
            echo "$RESPONSE" | jq '.name, .version'
          else
            echo "⚠️ Plugin not yet visible on marketplace (may take a few minutes)"
          fi

